In [24]:
import numpy as np
from sudoku import Sudoku
from itertools import product

In [87]:
def is_unique(lst):
    return lst.shape[0] == np.unique(lst).shape[0]

def can_put_number_at(x, y, n):
    global board
    
    board[x][y] = n
    row = board[x]
    col = board[:, y]
    res = is_unique(row[row != 0]) and is_unique(col[col != 0])

    ranges = [(0,3), (3,6), (6,9)]
    for left, right in product(ranges, ranges):
        current = board[left[0]:left[1], right[0]:right[1]]
        current = current[current != 0]
        res &= is_unique(current)

    board[x][y] = 0
    return res

can_put_number_at(4,4,3)

True

In [121]:
def solve():
    global board, solution_count
    for x in range(9):
        for y in range(9):
            if board[x][y] != 0:
                continue
            for n in range(1,10):
                if can_put_number_at(x, y, n):
                    board[x][y] = n
                    solve()
                    # backtracking step (revert to state before recursive call).
                    board[x][y] = 0
            return
    
    solution_count += 1
    print(f'\nSolution #{solution_count}')
    print(board, board[board != 0].shape[0])

In [122]:
puzzle = Sudoku(3).difficulty(.5)
board = np.array(puzzle.board)

solution_count = 0
board[board == None] = 0

print(f'Initial Board:\n{board}')
solve()

Initial Board:
[[6 0 0 1 0 3 4 0 0]
 [2 9 0 0 5 4 0 0 0]
 [3 0 4 0 9 0 0 0 7]
 [0 0 0 0 0 0 7 9 6]
 [1 6 7 0 0 9 8 0 2]
 [8 0 0 6 4 7 3 1 5]
 [5 1 0 3 7 2 0 0 4]
 [0 0 0 0 0 0 5 7 0]
 [7 4 0 9 0 5 0 6 0]]

Solution #1
[[6 7 5 1 8 3 4 2 9]
 [2 9 1 7 5 4 6 3 8]
 [3 8 4 2 9 6 1 5 7]
 [4 5 3 8 2 1 7 9 6]
 [1 6 7 5 3 9 8 4 2]
 [8 2 9 6 4 7 3 1 5]
 [5 1 6 3 7 2 9 8 4]
 [9 3 2 4 6 8 5 7 1]
 [7 4 8 9 1 5 2 6 3]] 81

Solution #2
[[6 7 8 1 2 3 4 5 9]
 [2 9 1 7 5 4 6 3 8]
 [3 5 4 8 9 6 1 2 7]
 [4 3 5 2 1 8 7 9 6]
 [1 6 7 5 3 9 8 4 2]
 [8 2 9 6 4 7 3 1 5]
 [5 1 6 3 7 2 9 8 4]
 [9 8 2 4 6 1 5 7 3]
 [7 4 3 9 8 5 2 6 1]] 81


In [123]:
res = puzzle.solve()

In [124]:
res.show_full()


---------------------------
9x9 (3x3) SUDOKU PUZZLE
Difficulty: SOLVED
---------------------------
+-------+-------+-------+
| 6 7 5 | 1 8 3 | 4 2 9 |
| 2 9 1 | 7 5 4 | 6 3 8 |
| 3 8 4 | 2 9 6 | 1 5 7 |
+-------+-------+-------+
| 4 5 3 | 8 2 1 | 7 9 6 |
| 1 6 7 | 5 3 9 | 8 4 2 |
| 8 2 9 | 6 4 7 | 3 1 5 |
+-------+-------+-------+
| 5 1 6 | 3 7 2 | 9 8 4 |
| 9 3 2 | 4 6 8 | 5 7 1 |
| 7 4 8 | 9 1 5 | 2 6 3 |
+-------+-------+-------+

        
